### ISSUE TITLE
Add RN example

### ISSUE THREAD

**Issue by pederjohnsen** [thinkproductivity/emoji-mart-native#6]

**Comment by ex7r3me** [comment]
@pederjohnsen do you have anything in mind for the sample app? I can help with making a sample app for android

**Comment by pederjohnsen** [comment]
@ex7r3me I was really just thinking of doing something similar to how `emoji-mart` does it with this: https://missive.github.io/emoji-mart/, basically just showcasing how the actual picker looks/works.. Preferably having the source run on both iOS and android too so only one example app is needed.

**Comment by ex7r3me** [comment]
@pederjohnsen we can use an RN Picker component to choose the set and show the emoji picker and then the selected emoji just like the emoji-mart demo. 
I agree with the single source code for both iOS and Android and it shouldn't be a problem as it's react native, I think I can find a Mac and test the app on iOS too if you aren't on this issue already.

**Comment by pederjohnsen** [comment]
@ex7r3me sounds good, if you take it on and have any issues regarding the `localImages` stuff just give me a shout, can't remember if the readme explains the implementation well enough yet (think it will best to use it, as using online sources doesn't work very well) I'll be able to test on both android/iOS if required :ok_hand:

**Comment by ex7r3me** [comment]
@pederjohnsen nice, I take it. I need to get `localImages` working for another project too, so I'll check it and let you know if any help needed. thank you 👍

**Comment by ex7r3me** [comment]
Hey @pederjohnsen! I've made a sample app in my forked repository [here](https://github.com/ex7r3me/emoji-mart-native), is it good to open a PR to review or you'll checkout from there?
about the local images, I used [emoji-data](https://github.com/iamcal/emoji-data) but it seems they have removed the `emojione` from their repository due to some licensing issues [explained here](https://github.com/iamcal/emoji-data/pull/142).
so I couldn't use the `all.js` file and had to do some hacky way to include all data, please let me know if there's another way.
to get local images work I had to copy images from `emoji-data` but they have a for example `npm install emoji-datasource-apple` command to install a single set, we may able to use this and give paths relative to `node_modules` for images to make installation easier and keep example directory lighter (it has ~45MB assets folder).

**Comment by ex7r3me** [comment]
Thanks @pederjohnsen 
I'd open a PR, update me about changes need to be done. I would be happy to make it better 😊
I saw the issues about the `emojione` and npm packages, let me know if could give any help there 👍
